// batch2/svelte-batch/src/components/BatchTable.svelte
<script lang='ts'>
  import { Link } from 'svelte-navigator'
  import type { Batch } from '@hail/common/types'
  export let batches: Batch[]
</script>

<h1>Batches</h1>
<ul>
  {#each batches as batch}
    <li>
      <Link to={`/batches/${batch.id}`}>{batch.id}</Link>
      <span>{batch.state}</span>
    </li>
  {/each}
</ul>

// batch2/react-batch/src/components/BatchTable.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import type { Batch } from '@hail/common/types';

function BatchTableRow({ batch }: { batch: Batch }) {
  return (
    <>
      <Link to={`/batches/${batch.id}`}>{batch.id}</Link>
      <span>{batch.state}</span>
    </>
  );
}

export default function BatchTable({ batches }: { batches: Batch[] }) {
  return (
    <ul>
      {batches.map((b) => <li key={b.id}><BatchTableRow batch={b} /></li>)}
    </ul>
  );
}
