// batch2/react-batch/src/pages/BatchesPage.tsx
import React from 'react';
import { useBatches } from '@hail/common/react/batch-client';
import BatchTable from '../components/BatchTable';

export default function BatchesPage() {
  const batches = useBatches();

  return (
    <>
      <h1>Batches</h1>
      {batches ? <BatchTable batches={batches.batches} /> : <div>Loading...</div>}
    </>
  );
}

// batch2/svelte-batch/src/pages/BatchesPage.svelte
<script lang='ts'>
  import { onDestroy } from 'svelte'
  import { getBatchesStore } from '@hail/common/svelte/batch-client'
  import type { Maybe, Batch } from '@hail/common/types'
  import BatchTable from '../components/BatchTable.svelte'

  let batches: Maybe<Batch[]> = undefined
  let { store, destroy } = getBatchesStore()

  const unsubscribe = store.subscribe(msg => {
    batches = msg?.batches
  })

  onDestroy(() => {
    unsubscribe()
    destroy()
  })
</script>

{#if batches}
  <BatchTable batches={batches} />
{:else}
  <div>Loading...</div>
{/if}
