// batch2/svelte-batch/src/pages/BatchPage.svelte
<script lang='ts'>
  import { onDestroy } from 'svelte'
  import { getJobsStore } from '@hail/common/svelte/batch-client'
  import JobTable from '../components/JobTable.svelte'
  import type { Maybe, Job } from '@hail/common/types'

  export let id: number;

  let jobs: Maybe<Job[]> = undefined;
  const { store, destroy } = getJobsStore(id)
  const unsubscribe = store.subscribe(msg => {
    jobs = msg?.jobs
  })

  onDestroy(() => {
    unsubscribe()
    destroy()
  })
</script>

{#if jobs}
  <JobTable jobs={jobs} batchId={id} />
{:else}
  <div>Loading...</div>
{/if}

// batch2/react-batch/src/pages/BatchPage.tsx
import React from 'react';
import { useParams } from 'react-router-dom';
import { useJobs } from '@hail/common/react/batch-client';
import JobTable from '../components/JobTable';

import '@hail/common/hail.css';

type BatchPageParams = { id?: string };
export default function BatchPage() {
  const id = parseInt(useParams<BatchPageParams>().id!, 10);
  const jobs = useJobs(id);

  return jobs ? <JobTable batchId={id} jobs={jobs.jobs} /> : <div>Loading...</div>;
}
