// batch2/svelte-batch/src/App.svelte
<script lang="ts">
  import { Router, Route } from 'svelte-navigator'
  import '@hail/common/hail.css'
  import BatchesPage from './pages/BatchesPage.svelte'
  import BatchPage from './pages/BatchPage.svelte'
</script>

<main>
  <Router>
    <header class="App">
      <Route exact path="/batches/:id" let:params>
        <BatchPage id={parseInt(params.id)} />
      </Route>
      <Route exact path="/">
        <BatchesPage />
      </Route>
      <Route exact path="*">
        <p>Uh oh! That page does not exist...</p>
      </Route>
    </header>
  </Router>
</main>

// batch2/react-batch/src/App.tsx
import React from 'react';
import { Switch, Route } from 'react-router-dom';
import BatchPage from './pages/BatchPage';
import BatchesPage from './pages/BatchesPage';

import '@hail/common/hail.css';

export default function App() {
  return (
    <div>
      <header className="App">
        <Switch>
          <Route exact path="/batches/:id" component={BatchPage} />
          <Route exact path="/" component={BatchesPage} />
          <Route exact path="*" component={BadRoute} />
        </Switch>
      </header>
    </div>
  );
}

function BadRoute() {
  return <p>Uh oh! That page does not exist...</p>;
}
